### PR TITLE
[Fix] Divider View theme import issue

### LINKED ISSUE #218: DividerView cannot import colors correctly, prompting that "Module not found: Can't resolve 'react-native-elements/src/config/theme' in..."
As title

```
diff --git a/src/views/Divider.tsx b/src/views/Divider.tsx
index 14166c8..5dce514 100644
--- a/src/views/Divider.tsx
+++ b/src/views/Divider.tsx
@@ -2,7 +2,7 @@ import React from 'react';
 import { Text, Divider } from 'react-native-elements';
 import { ScrollView, StyleSheet, View } from 'react-native';
 import { Header, SubHeader } from '../components/header';
-import theme from 'react-native-elements/src/config/theme';
+import colors from '../config/colors';

 type DividerViewTypes = {};

@@ -18,7 +18,7 @@ const DividerView: React.FunctionComponent<DividerViewTypes> = (props) => {
           <Text style={styles.horizontalText}>
             Horizontal Divider with width and color
           </Text>
-          <Divider width={5} color={theme.colors.primary} />
+          <Divider width={5} color={colors.primary} />
         </View>
         <SubHeader title="Horizontal Divider with Inset" />
         <View style={styles.horizontal}>
@@ -53,7 +53,7 @@ const DividerView: React.FunctionComponent<DividerViewTypes> = (props) => {
           <Divider
             subHeader="Divider"
             inset={true}
-            subHeaderStyle={{ color: theme.colors.primary }}
+            subHeaderStyle={{ color: colors.primary }}
           />
           <Text style={styles.horizontalText}>Right text</Text>
         </View>

```

### PR DESCRIPTION
**Pull request by khushal87**
Fixes #218

### CODE REVIEW

File: src/views/Divider.tsx [hunk 1]
```diff
@@ -1,12 +1,12 @@
-import React from 'react';
-import { Text, Divider } from 'react-native-elements';
+import React, { useContext } from 'react';
+import { Text, Divider, ThemeContext } from 'react-native-elements';
```
Comment (arpitBhalla) [inline src/views/Divider.tsx]: `useTheme` looks more nicer

**Review by arpitBhalla — CHANGES_REQUESTED** [review]

File: src/views/Divider.tsx (hunk 1 above)
Comment (khushal87) [reply src/views/Divider.tsx]: Okay, I will see and implement that way. Thanks @arpitBhalla
